name = "DoonCraft Vanilla+"
author = "doonguy"
version = "1.1.1a"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "991e7f217dae1575000dc3977b37d5188b04d2c2197dee2dc239cced24b870ae"

[versions]
fabric = "0.15.7"
minecraft = "1.20.4"
